# IMPORT MODULE

In [24]:
import numpy as np
import time

# SECTION 1: ARRAY CREATION, INDEXING, AND SLICING


## Array Creation

In [25]:
# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"1D Array:\n{arr_1d}")
print(f"Shape: {arr_1d.shape}, Dimensions: {arr_1d.ndim}, Size: {arr_1d.size}\n")

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,), Dimensions: 1, Size: 10



In [26]:
# 2D Array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(f"2D Array:\n{arr_2d}")
print(f"Shape: {arr_2d.shape}, Dimensions: {arr_2d.ndim}, Size: {arr_2d.size}\n")

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4), Dimensions: 2, Size: 12



In [27]:
# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr_3d}")
print(f"Shape: {arr_3d.shape}, Dimensions: {arr_3d.ndim}, Size: {arr_3d.size}\n")

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2), Dimensions: 3, Size: 8



In [28]:
# Special Arrays
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 3, 4))
identity_arr = np.eye(4)
range_arr = np.arange(0, 20, 2)
linspace_arr = np.linspace(0, 10, 5)
random_arr = np.random.randint(1, 100, size=(4, 5))

print(f"Zeros Array (3x4):\n{zeros_arr}\n")
print(f"Identity Matrix (4x4):\n{identity_arr}\n")
print(f"Range Array (0 to 20, step 2):\n{range_arr}\n")
print(f"Linspace Array (0 to 10, 5 points):\n{linspace_arr}\n")
print(f"Random Array (4x5, values 1-99):\n{random_arr}\n")

Zeros Array (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Range Array (0 to 20, step 2):
[ 0  2  4  6  8 10 12 14 16 18]

Linspace Array (0 to 10, 5 points):
[ 0.   2.5  5.   7.5 10. ]

Random Array (4x5, values 1-99):
[[92 36 70  5 81]
 [48 62 80 97 70]
 [53 64 58 72 99]
 [30 24 84  2 76]]



## Indexing

In [29]:
print("\n1.2 Indexing Operations:")
print(f"Original 2D Array:\n{arr_2d}\n")
print(f"Element at [1, 2]: {arr_2d[1, 2]}")
print(f"First row: {arr_2d[0]}")
print(f"Last column: {arr_2d[:, -1]}")
print(f"Element at [-1, -1]: {arr_2d[-1, -1]}\n")


1.2 Indexing Operations:
Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [1, 2]: 7
First row: [1 2 3 4]
Last column: [ 4  8 12]
Element at [-1, -1]: 12



## Slicing

In [30]:
print(f"Original 1D Array: {arr_1d}")
print(f"Elements [2:7]: {arr_1d[2:7]}")
print(f"Every 2nd element: {arr_1d[::2]}")
print(f"Reversed array: {arr_1d[::-1]}\n")

print(f"Original 2D Array:\n{arr_2d}")
print(f"\nFirst 2 rows, first 3 columns:\n{arr_2d[:2, :3]}")
print(f"\nEvery other row:\n{arr_2d[::2, :]}")
print(f"\nLast 2 rows, last 2 columns:\n{arr_2d[-2:, -2:]}\n")

# Boolean Indexing
mask = random_arr > 50
print(f"Boolean Mask (values > 50):\n{mask}")
print(f"Filtered values: {random_arr[mask]}\n")

Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10]
Elements [2:7]: [3 4 5 6 7]
Every 2nd element: [1 3 5 7 9]
Reversed array: [10  9  8  7  6  5  4  3  2  1]

Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First 2 rows, first 3 columns:
[[1 2 3]
 [5 6 7]]

Every other row:
[[ 1  2  3  4]
 [ 9 10 11 12]]

Last 2 rows, last 2 columns:
[[ 7  8]
 [11 12]]

Boolean Mask (values > 50):
[[ True False  True False  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [False False  True False  True]]
Filtered values: [92 70 81 62 80 97 70 53 64 58 72 99 84 76]



# SECTION 2: MATHEMATICAL, AXIS-WISE, AND STATISTICAL OPERATIONS


In [31]:
# Create sample dataset for analysis
np.random.seed(42)
sales_data = np.random.randint(100, 1000, size=(12, 4))  # 12 months, 4 products
print(f"\nSample Dataset - Monthly Sales Data (12 months x 4 products):\n{sales_data}\n")


Sample Dataset - Monthly Sales Data (12 months x 4 products):
[[202 535 960 370]
 [206 171 800 120]
 [714 221 566 314]
 [430 558 187 472]
 [199 971 763 230]
 [761 408 869 443]
 [591 513 905 485]
 [291 376 260 559]
 [413 121 352 847]
 [956 660 574 158]
 [610 781 575 799]
 [882 289 786 662]]



In [32]:
arr_a = np.array([10, 20, 30, 40, 50])
arr_b = np.array([1, 2, 3, 4, 5])

print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Addition (A + B): {arr_a + arr_b}")
print(f"Subtraction (A - B): {arr_a - arr_b}")
print(f"Multiplication (A * B): {arr_a * arr_b}")
print(f"Division (A / B): {arr_a / arr_b}")
print(f"Power (A ** 2): {arr_a ** 2}")
print(f"Square Root: {np.sqrt(arr_a)}")
print(f"Exponential: {np.exp(arr_b)}")
print(f"Logarithm: {np.log(arr_a)}\n")

Array A: [10 20 30 40 50]
Array B: [1 2 3 4 5]
Addition (A + B): [11 22 33 44 55]
Subtraction (A - B): [ 9 18 27 36 45]
Multiplication (A * B): [ 10  40  90 160 250]
Division (A / B): [10. 10. 10. 10. 10.]
Power (A ** 2): [ 100  400  900 1600 2500]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]



In [33]:
# 2.2 Axis-wise Operations
print("\n2.2 Axis-wise Operations on Sales Data:")
print("-" * 40)

monthly_total = np.sum(sales_data, axis=1)  # Sum across products (axis=1)
product_total = np.sum(sales_data, axis=0)  # Sum across months (axis=0)

print(f"Monthly Total Sales (sum across products):\n{monthly_total}\n")
print(f"Product Total Sales (sum across months):\n{product_total}\n")

monthly_avg = np.mean(sales_data, axis=1)
product_avg = np.mean(sales_data, axis=0)

print(f"Monthly Average Sales:\n{monthly_avg}\n")
print(f"Product Average Sales:\n{product_avg}\n")


2.2 Axis-wise Operations on Sales Data:
----------------------------------------
Monthly Total Sales (sum across products):
[2067 1297 1815 1647 2163 2481 2494 1486 1733 2348 2765 2619]

Product Total Sales (sum across months):
[6255 5604 7597 5459]

Monthly Average Sales:
[516.75 324.25 453.75 411.75 540.75 620.25 623.5  371.5  433.25 587.
 691.25 654.75]

Product Average Sales:
[521.25       467.         633.08333333 454.91666667]



In [34]:
# 2.3 Statistical Operations
print("\n2.3 Statistical Analysis:")
print("-" * 40)

print(f"Overall Statistics:")
print(f"  Total Sales: {np.sum(sales_data)}")
print(f"  Mean: {np.mean(sales_data):.2f}")
print(f"  Median: {np.median(sales_data):.2f}")
print(f"  Standard Deviation: {np.std(sales_data):.2f}")
print(f"  Variance: {np.var(sales_data):.2f}")
print(f"  Min Value: {np.min(sales_data)}")
print(f"  Max Value: {np.max(sales_data)}")
print(f"  25th Percentile: {np.percentile(sales_data, 25):.2f}")
print(f"  75th Percentile: {np.percentile(sales_data, 75):.2f}\n")

# Product-wise statistics
print(f"Product-wise Statistics:")
for i in range(sales_data.shape[1]):
    print(f"  Product {i+1}: Mean={np.mean(sales_data[:, i]):.2f}, "
          f"Std={np.std(sales_data[:, i]):.2f}, "
          f"Min={np.min(sales_data[:, i])}, "
          f"Max={np.max(sales_data[:, i])}")

# Correlation matrix
correlation_matrix = np.corrcoef(sales_data.T)
print(f"\nCorrelation Matrix between Products:\n{correlation_matrix}\n")

# Cumulative operations
cumulative_sales = np.cumsum(sales_data, axis=0)
print(f"Cumulative Sales (first 3 months):\n{cumulative_sales[:3]}\n")


2.3 Statistical Analysis:
----------------------------------------
Overall Statistics:
  Total Sales: 24915
  Mean: 519.06
  Median: 524.00
  Standard Deviation: 254.02
  Variance: 64524.68
  Min Value: 120
  Max Value: 971
  25th Percentile: 290.50
  75th Percentile: 761.50

Product-wise Statistics:
  Product 1: Mean=521.25, Std=258.96, Min=199, Max=956
  Product 2: Mean=467.00, Std=244.30, Min=121, Max=971
  Product 3: Mean=633.08, Std=247.18, Min=187, Max=960
  Product 4: Mean=454.92, Std=224.57, Min=120, Max=847

Correlation Matrix between Products:
[[ 1.         -0.06783523  0.0587169   0.12243663]
 [-0.06783523  1.          0.12026302 -0.17156347]
 [ 0.0587169   0.12026302  1.         -0.33854219]
 [ 0.12243663 -0.17156347 -0.33854219  1.        ]]

Cumulative Sales (first 3 months):
[[ 202  535  960  370]
 [ 408  706 1760  490]
 [1122  927 2326  804]]



# SECTION 3: RESHAPING AND BROADCASTING TECHNIQUES


In [35]:
# 3.1 Reshaping Operations
print("\n3.1 Reshaping Operations:")
print("-" * 40)

original = np.arange(1, 25)
print(f"Original 1D Array (24 elements):\n{original}\n")

reshaped_2d = original.reshape(4, 6)
print(f"Reshaped to 4x6:\n{reshaped_2d}\n")

reshaped_3d = original.reshape(2, 3, 4)
print(f"Reshaped to 2x3x4:\n{reshaped_3d}\n")

flattened = reshaped_3d.flatten()
print(f"Flattened back to 1D:\n{flattened}\n")

transposed = reshaped_2d.T
print(f"Transposed (6x4):\n{transposed}\n")

# Reshape with -1 (auto-calculate dimension)
auto_reshape = original.reshape(6, -1)
print(f"Auto-reshaped (6, -1) → shape {auto_reshape.shape}:\n{auto_reshape}\n")


3.1 Reshaping Operations:
----------------------------------------
Original 1D Array (24 elements):
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshaped to 4x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Reshaped to 2x3x4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Flattened back to 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Transposed (6x4):
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Auto-reshaped (6, -1) → shape (6, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



In [36]:
# 3.2 Broadcasting Techniques
print("\n3.2 Broadcasting Techniques:")
print("-" * 40)

# Example 1: Scalar broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Original Matrix:\n{matrix}\n")
print(f"Add scalar 10 (broadcasting):\n{matrix + 10}\n")


3.2 Broadcasting Techniques:
----------------------------------------
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Add scalar 10 (broadcasting):
[[11 12 13]
 [14 15 16]
 [17 18 19]]

